- 
  name: Admin
  url: '#'
  class: null
  sub:
    - 
      name: Usuarios
      url: user
    - 
      name: Configurar
      url: config
    - 
      name: Roles
      url: role
    - 
      name: Acciones
      url: action
    - 
      name: Recursos
      url: resource